# Generated by Django 6.0 on 2025-12-31 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nome', models.TextField(blank=True, null=True)),
                ('potencia_w', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gas_kg_h', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'db_table': 'maquinas',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('grupo', models.CharField(blank=True, max_length=50, null=True)),
                ('unidade', models.CharField(blank=True, max_length=10, null=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('estoque_atual', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('estoque_fundo', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('estoque_minimo', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('controla_estoque', models.BooleanField(default=True)),
                ('codigos_barras', models.JSONField(blank=True, default=list, null=True)),
                ('categoria', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produtos',
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('chave', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'tarifas',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('operador', models.CharField(blank=True, max_length=50, null=True)),
                ('itens', models.JSONField()),
            ],
            options={
                'db_table': 'vendas',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id_produto', models.OneToOneField(db_column='id_produto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='gestao.produto')),
                ('nome', models.TextField(blank=True, null=True)),
                ('rendimento', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('tempo_preparo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('margem_lucro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imposto_perc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custo_insumos', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('custo_maquinas', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('custo_mao_obra', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('custo_total_lote', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ingredientes', models.JSONField(blank=True, null=True)),
                ('maquinas_uso', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'receitas',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('nome_produto', models.TextField(blank=True, null=True)),
                ('qtd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('saldo_anterior', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('saldo_novo', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cod_produto', models.ForeignKey(blank=True, db_column='cod_produto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestao.produto')),
            ],
            options={
                'db_table': 'movimentacoes',
            },
        ),
    ]
